language: bash
sudo: required

services: docker

env:
  - PORTUS_VERSION=v2.0
  - PORTUS_VERSION=master

allow_failures:
    - env: PORTUS_VERSION=master

script:
   - ./update.sh $PORTUS_VERSION
   - docker build -t lonewulf/portus .

after_script:
   - docker images
