language: bash
sudo: required

services: docker

env:
  - PORTUS_VERSION=master

before_script:
  - docker -v

script:
   - ./update.sh $PORTUS_VERSION
   - docker build -t quay.io/lonewulf/portus .

after_script:
   - docker images

after_success:
  - packaging/quay.io/push.sh
