language: bash
sudo: required

services: docker

env:
  - PORTUS_VERSION=v2.0
  - PORTUS_VERSION=master

matrix:
  allow_failures:
    - env: PORTUS_VERSION=master

before_script:
  - docker -v
  - docker pull alpine:3.3
  - docker pull quay.io/lonewulf/portus
  - docker images
  - export OLD_HASH=$(docker images -q quay.io/lonewulf/portus)

script:
   - ./update.sh $PORTUS_VERSION
   - docker build -t quay.io/lonewulf/portus .

after_script:
   - docker images

after_success:
  - packaging/quay.io/push.sh
